name: Publish Image

on:
    push:
        tags:
            - '[0-9]+.*'

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Publish
            uses: HurricanKai/Publish-Docker-Github-Action@master
            if: contains(github.ref, 'refs/tags/[0-9]+.*')
            with:
              name: monolithprojects/github-action-molecule
              username: monolithprojects
              password: ${{ secrets.TOKEN }}
              tagging: true
              registry: docker.io
              dockerfile: Dockerfile
