name: Publish Image

on:
    push:
        tags:
            - 'v[0-9]+.*'

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Publish to Registry
            uses: elgohr/Publish-Docker-Github-Action@master
            with:
              name: monolithprojects/github-action-molecule
              username: monolithprojects
              password: ${{ secrets.TOKEN }}
              tag_semver: true
              registry: docker.io
              dockerfile: Dockerfile
